version: '3.8'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - ENV_VAR_NAME=value
#    volumes:
#      - .:/app
#    restart: unless-stopped
#    networks:
#      - report-management-network
#    depends_on:
#      - db

  db:
    image: mariadb:latest
    container_name: database-report-management
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: grainecap
      MYSQL_ROOT_PASSWORD: X0AhfRCK8GMeHfx2
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - report-management-network

#  nginx:
#    image: nginx:alpine
#    container_name: scrib-nginx
#    restart: unless-stopped
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./:/var/www
#      - ./docker-compose/nginx:/etc/nginx/conf.d/
#      - /etc/letsencrypt:/etc/letsencrypt
#    networks:
#      - report-management-network

networks:
  report-management-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
